// Generated by CoffeeScript 2.3.2
(function() {
  window.畫面 = {
    詞列: [],
    當前混淆: ['q', 'w', 'e'],
    正解位置: 0,
    入詞: function(單詞) {
      return this.詞列.push(單詞);
    },
    入混淆: function(混淆) {
      return this.當前混淆 = 混淆;
    },
    當前單詞: function() {
      return this.詞列.slice(-2, -1)[0];
    },
    來: function(單詞, 混淆) {
      this.入詞(單詞);
      this.入混淆(混淆);
      return this.更新畫面();
    },
    更新畫面: function() {
      var i, j, k, l, len, len1, len2, m, n, ref, ref1, ref2, s;
      console.log(this.當前混淆);
      s = '';
      ref = this.詞列.slice(-8, -2);
      for (k = 0, len = ref.length; k < len; k++) {
        i = ref[k];
        s += `<p><span class='單詞'>${i.單詞}</span><br>${i.意思}</p>`;
      }
      ref1 = this.詞列.slice(-2, -1);
      for (l = 0, len1 = ref1.length; l < len1; l++) {
        i = ref1[l];
        s += `<p class='當前詞'><span class='單詞'>${i.單詞}</span></p>`;
      }
      ref2 = this.詞列.slice(-1);
      for (m = 0, len2 = ref2.length; m < len2; m++) {
        i = ref2[m];
        s += `<p class='下個詞'><span class='單詞'>${i.單詞}</span></p>`;
      }
      $('#單詞條').html(s);
      this.正解位置 = Math.ceil(Math.random() * 4);
      j = 0;
      for (i = n = 1; n <= 4; i = ++n) {
        if (i === this.正解位置) {
          continue;
        }
        $(`#選項.${i} > div`).html(this.當前混淆[j]);
        console.log('位置', i, j, this.當前混淆[j]);
        j += 1;
      }
      return $(`#選項.${this.正解位置} > div`).html(this.當前單詞().意思);
    },
    選擇: function(x) {
      if (x === this.正解位置) {
        return 山彥.下一題();
      }
    }
  };

  $(function() {
    山彥.初始化();
    $(`#選項.${1}`).click(function() {
      return 畫面.選擇(1);
    });
    $(`#選項.${2}`).click(function() {
      return 畫面.選擇(2);
    });
    $(`#選項.${3}`).click(function() {
      return 畫面.選擇(3);
    });
    return $(`#選項.${4}`).click(function() {
      return 畫面.選擇(4);
    });
  });

}).call(this);
