// Generated by CoffeeScript 2.3.2
(function() {
  window.畫面 = {
    詞列: [],
    切列: [],
    當前混淆: ['q', 'w', 'e'],
    正解位置: 0,
    靜音: false,
    入詞: function(單詞) {
      return this.詞列.push(單詞);
    },
    入混淆: function(混淆) {
      return this.當前混淆 = 混淆;
    },
    當前單詞: function() {
      return this.詞列.slice(-2, -1)[0];
    },
    來: function(單詞, 混淆) {
      this.入詞(單詞);
      this.入混淆(混淆);
      return this.更新畫面();
    },
    切: function(單詞) {
      this.切列.push(單詞);
      $('head').append(`<style>.單詞--${單詞}{opacity: 0.2 !important;}</style>`);
      return 山彥.切(單詞);
    },
    更新畫面: function() {
      var i, j, k, l, len, len1, len2, m, n, ref, ref1, ref2, s;
      console.log(this.當前混淆);
      s = '';
      ref = this.詞列.slice(-16, -2);
      for (k = 0, len = ref.length; k < len; k++) {
        i = ref[k];
        s += `<p class='之前詞 單詞--${i.單詞}'>\n    <a href='javascript:畫面.切("${i.單詞}");'>\n        <i class='fa fa-low-vision'></i>\n    </a> \n    <span class='單詞'>${i.單詞}</span>\n    <span class='詞頻 太陽交換'>\n        <span class='對數'>\n            ${Math.floor(Math.log(i.信息.ecdict信息.frq / 1024 + 0.5) / Math.log(2) + 2)}\n        </span>\n        <span class='數'>\n            詞頻順序: ${i.信息.ecdict信息.frq}\n        </span>\n    </span>\n    <br/>\n    <span class='單詞信息 太陽交換'>\n        <span class='例句'>\n            ${i.信息.例句[1]}\n            <br/>\n            ${i.信息.例句[0]}\n        </span>\n        <span class='意思'>\n            ${i.信息.意思}\n        </span>\n    </span>\n</p>`;
      }
      ref1 = this.詞列.slice(-2, -1);
      for (l = 0, len1 = ref1.length; l < len1; l++) {
        i = ref1[l];
        s += `<p class='當前詞 太陽交換'>\n    <span class='單詞'>\n        ${i.單詞}\n    </span>\n    <span class='例句'>\n        ${i.信息.例句[0]}\n    </span>\n</p>`;
      }
      ref2 = this.詞列.slice(-1);
      for (m = 0, len2 = ref2.length; m < len2; m++) {
        i = ref2[m];
        s += `<p class='下個詞'><span class='單詞'>${i.單詞}</span></p>`;
      }
      $('#單詞條').html(s);
      this.正解位置 = Math.ceil(Math.random() * 4);
      j = 0;
      for (i = n = 1; n <= 4; i = ++n) {
        if (i === this.正解位置) {
          continue;
        }
        $(`#選項.${i} > div`).html(this.當前混淆[j]);
        console.log('位置', i, j, this.當前混淆[j]);
        j += 1;
      }
      return $(`#選項.${this.正解位置} > div`).html(this.當前單詞().信息.意思);
    },
    選擇: function(x) {
      if (x === this.正解位置) {
        v.已選長度 += 1;
        if (!this.靜音) {
          琴.叮();
        }
        return 山彥.下一題();
      } else {
        if (!this.靜音) {
          return 琴.連彈([7, 6, 5, 4, 3, 2, 1], 0.18, 25);
        }
      }
    },
    單詞縮小: function() {
      return $("#單詞條").addClass('縮小');
    },
    單詞還原: function() {
      return $("#單詞條").removeClass("縮小");
    }
  };

  $(function() {
    var f;
    f = function() {
      var d;
      d = new Date();
      $('#時').html(d.getHours());
      if (d.getMinutes() >= 10) {
        $('#分').html(d.getMinutes());
      } else {
        $('#分').html("0" + d.getMinutes());
      }
      return setTimeout(f, 1000);
    };
    f();
    window.v = new Vue({
      el: '#all',
      data: {
        畫面: 畫面,
        詞典長度: 0,
        切表長度: 0,
        已選長度: 0
      },
      watch: {
        $data: {
          handler: function(val, oldVal) {
            return 山彥.vue更新(val);
          },
          deep: true
        }
      }
    });
    山彥.vue連接初始化(function(x) {
      var a, b, results;
      results = [];
      for (a in x) {
        b = x[a];
        results.push(v[a] = b);
      }
      return results;
    });
    return 山彥.初始化();
  });

}).call(this);
